#!/usr/bin/env python3
"""从论文 frontmatter 生成 indices/ 静态 markdown。幂等全量重写。

用法：python3 scripts/build_indices.py [repo_root]   (默认当前目录)
"""
import os
import sys
import re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_frontmatter as fm
import lib_render as render

AUTO_HEADER = "<!-- AUTO-GENERATED by scripts/build_indices.py, 勿手改自动区 -->"
AUTO_START = "<!-- AUTO:start -->"
AUTO_END = "<!-- AUTO:end -->"
MANUAL_START = "<!-- MANUAL:start -->"
MANUAL_END = "<!-- MANUAL:end -->"


def write_full(path, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(AUTO_HEADER + "\n\n" + body.rstrip() + "\n")


def _new_semi_auto(body):
    return (
        AUTO_HEADER + "\n\n"
        + AUTO_START + "\n" + body.rstrip() + "\n" + AUTO_END + "\n\n"
        + MANUAL_START + "\n\n" + MANUAL_END + "\n"
    )


def splice_auto_block(path, body):
    if not os.path.exists(path):
        return _new_semi_auto(body)
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    if AUTO_START in text and AUTO_END in text:
        pattern = re.compile(
            re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), re.DOTALL
        )
        replacement = AUTO_START + "\n" + body.rstrip() + "\n" + AUTO_END
        return pattern.sub(lambda _m: replacement, text, count=1)
    # 既有文件但没有自动块：保留原内容为 MANUAL，前置自动块
    return (
        AUTO_HEADER + "\n\n"
        + AUTO_START + "\n" + body.rstrip() + "\n" + AUTO_END + "\n\n"
        + MANUAL_START + "\n" + text.rstrip() + "\n" + MANUAL_END + "\n"
    )


def _write_semi(path, body):
    new = splice_auto_block(path, body)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(new)


def _comparisons_listing(repo_root):
    comp_dir = os.path.join(repo_root, "comparisons")
    lines = ["## 对比报告清单"]
    if not os.path.isdir(comp_dir):
        return "\n".join(lines)
    paths = []
    for root, _dirs, files in os.walk(comp_dir):
        for fn in files:
            if fn.endswith(".md") and not fn.startswith("_"):
                rel = os.path.relpath(os.path.join(root, fn), repo_root)
                paths.append(rel.replace(os.sep, "/"))
    for rel in sorted(paths):
        lines.append("- [{}]({})".format(rel, "../" + rel))
    return "\n".join(lines)


def main(repo_root="."):
    papers_dir = os.path.join(repo_root, "papers")
    idx = os.path.join(repo_root, "indices")
    papers = fm.load_papers(papers_dir)

    write_full(os.path.join(idx, "timeline.md"), render.render_timeline(papers))
    write_full(os.path.join(idx, "landmarks.md"), render.render_landmarks(papers))

    _write_semi(os.path.join(idx, "papers.md"), render.render_papers_table(papers))
    _write_semi(os.path.join(idx, "directions.md"), render.render_directions(papers))
    _write_semi(os.path.join(idx, "methods.md"), render.render_methods(papers))
    _write_semi(os.path.join(idx, "comparisons.md"), _comparisons_listing(repo_root))

    print("索引已生成：{} 篇论文".format(len(papers)))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
